#!/bin/bash
arr=(51 49 47 44 43 41 39 38 37 35 33 31 29 27 25 24 23 19 18 17 15 14 13 11)
#arr=(19 18 17 15 14 13 12 11 9 8 7 6 5 4 3 2 1)
for var in ${arr[@]}
do
#ssh zl4dc@shen-$var "cd /localtmp/experiment_zl/namenode/bin; chmod a+x *; echo 'shen-'$var' result'; ls -al;"
ssh zl4dc@shen-$var "jps | grep DataNode; echo 'shen-'$var' result';"
done
#mkdir /localtmp/experiment_zl; cd /localtmp/experiment_zl/; cp -r ~/namenode ./;cd /localtmp/experiment_zl/; cd namenode/bin; ls -l; chmod a+x *;

