#!/bin/bash
rm -rf /localtmp/experiment_zl/namenode
rm -rf /localtmp/experiment_zl/hadoop_tmp
cp -r ~/namenode /localtmp/experiment_zl
cd /localtmp/experiment_zl/namenode/etc/hadoop
rm -rf core-site.xml yarn-site.xml hdfs-site.xml mapred-site.xml
cp ~/hadoop_setting/hdfs-site.xml ./
cp ~/hadoop_setting/mapred-site.xml ./
cp ~/hadoop_setting/yarn-site.xml ./
cp ~/hadoop_setting/core-site.xml ./
cd /localtmp/experiment_zl/namenode/bin
chmod a+x *
/localtmp/experiment_zl/namenode/bin/hdfs namenode -format
