#!/bin/bash
source `dirname $0`/config.sh

for((i=($1-1);i<=($2-1);i++))
do
$EXPERIMENT_SSH ${EXPERIMENT_MACHINES[$i]} "nohup $EXPERIMENT_DIR/namenode/bin/hdfs datanode &>$EXPERIMENT_DIR/log/datanode &" &
$EXPERIMENT_SSH ${EXPERIMENT_MACHINES[$i]} "$EXPERIMENT_DIR/scripts/test"
#sleep 1s
done
