#!/bin/bash
arr=(51 49 47 44 43 41 39 38 37 35 33 31 29 27 25 24 23 19 18 17 15 14 13 12 11)
#arr=(51)
for var in ${arr[@]}
do
ssh zl4dc@shen-$var "rm -rf /localtmp/experiment_zl/hadoop_tmp;echo 'shen-'$var' result'; ls /localtmp/experiment_zl"
done
