#!/bin/bash

cd /localtmp/experiment_zl/
dd if=/dev/zero of=$1.file bs=1M count=$1

cd /localtmp/experiment_zl/namenode/bin
./hadoop fs -put /localtmp/experiment_zl/$1.file /
cd /localtmp/experiment_zl/
rm -rf ./$1.file
