#!/bin/bash
source $(dirname $0)/config.sh
cd $EXPERIMENT_SCRIPT_DIR

i=1
for var in ${EXPERIMENT_NODE_COUNTS[@]}
do

echo "start experiment "$i
./update
sleep 120s
echo "update done"

./replace
sleep 20s
echo "replace done"

./start-namenode
sleep 10s
echo "start namenode done"

./start-alldn 1 2
sleep 10s
./upload 2000
sleep 30s

./start-alldn 3 4
sleep 10s
./upload 1000
sleep 20s

./start-alldn 5 6
sleep 10s
./upload 500
sleep 15s

./start-alldn 7 24
sleep 60s
./upload 501
sleep 15s
echo "initialize datanode done"


cd $EXPERIMENT_CHORD_SRC
java Test 24
echo "start balancing"

for((j=1;j<=var;j++))
do
timeout 1500 ~/scripts/10percent $j &
done
sleep 1500

echo "experiment "$i" done"

cd $EXPERIMENT_LOG_DIR
cp ./namenode ~/experiment
cd ~/experiment
mv ./namenode ./ex$i
echo "save experiment result done"

./del-all
sleep 20s
./stop-all
sleep 60s
kill -9 $(cat $EXPERIMENT_LOG_DIR/log/pids)
echo "shut down datanode and namenode done"
((i++))

done
