EXPERIMENT_DIR=$(realpath $(dirname ${BASH_SOURCE[0]})/..)
declare -a EXPERIMENT_DIRS EXPERIMENT_MACHINES EXPERIMENT_IDS
for i in $(seq 0 3); do
    EXPERIMENT_IDS[$i]=$i
    EXPERIMENT_DIRS[$i]=/localtmp/balancing-local/node-$i
    EXPERIMENT_MACHINES[$i]=localhost
done
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export JAVA_HOME
EXPERIMENT_HADOOP_TGZ=$EXPERIMENT_DIR/hadoop-2.8.5.tar.gz
EXPERIMENT_HADOOP_TGZ_DIR=hadoop-2.8.5
EXPERIMENT_SSH="ssh"
EXPERIMENT_TEMPLATE_DIR=$EXPERIMENT_DIR/templates
EXPERIMENT_LOG_DIR=$EXPERIMENT_DIR/log
EXPERIMENT_SCRIPT_DIR=$EXPERIMENT_DIR/scripts
EXPERIMENT_HADOOP_CONFIG_DIR=$EXPERIMENT_DIR/hadoop-configs
EXPERIMENT_CHORD_SRC=XXX # FIXME

EXPERIMENT_NODE_COUNTS=(4 4)

ssh_into_id() {
    local i=$1
    shift
    $EXPERIMENT_SSH ${EXPERIMENT_MACHINES[$i]} ". ${EXPERIMENT_DIRS[$i]-$EXPERIMENT_DIR}/scripts/config.sh; ${@}" 
}
