#!/bin/bash
source $(dirname $0)/config.sh
cd $EXPERIMENT_DIR/hadoop/bin
chmod a+x *
rm -r $EXPERIMENT_DIR/hadoop_tmp/dfs
./hdfs namenode -format
for i in ${EXPERIMENT_IDS[@]}; do
    ssh_into_id $i 'rm -r $EXPERIMENT_DIR/hadoop_tmp/dfs'
done
